### ISSUE TITLE
Merge Geo-Browser to production

### ISSUE THREAD

**Issue by emanueldima** [clarin-eric/switchboard-tool-registry#68]
It takes as input geographical information in the form of kml or csv files.

**Comment by fungunga** [comment]
Just two questions before production merge:
1. Can I give the language param via URL parameter, so that users do not have to chose a language before they see the Geo-Browser tool in the Switchboard? I already removed the language setting in the tool-registry… or maybe the tool can be displayed without chosen language?
2. I added another mimetype to the tool-registry a few days ago, and I can not see it in the tool inventory <https://weblicht.sfs.uni-tuebingen.de/switchboard-test/tools> (no problem, if it was not yet deployed :-)

**Comment by emanueldima** [comment]
1. The easy way is to remove all the strings in the `language` array, make it completely empty. This is the current method for the tools to signal that they do not require a language entry. (I think we have to rethink the profiles to make them more user friendly)

2. I have to update the tools in the dev version manually, now it's done :)

**Comment by fungunga** [comment]
1. Is it correct the tools won't validate then?

2. thanks!

**Comment by fungunga** [comment]
1. pull request started :-)

**Comment by emanueldima** [comment]
Issue fixed in #73

**Comment by emanueldima** [comment]
It's been already merged.
